import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-surface-variant': '#474555',
        'surface-container': '#eeecff',
        'on-primary-fixed': '#150066',
        'on-primary': '#ffffff',
        'surface-bright': '#fbf8ff',
        'secondary-fixed': '#ffe081',
        'on-secondary': '#ffffff',
        surface: '#fbf8ff',
        background: '#fbf8ff',
        'on-primary-fixed-variant': '#3e25c3',
        'inverse-surface': '#2e2f44',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'on-secondary-fixed-variant': '#564500',
        'tertiary-container': '#737381',
        'inverse-on-surface': '#f1efff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#191a2e',
        'secondary-container': '#fcd344',
        'on-secondary-container': '#715b00',
        'outline-variant': '#c8c4d7',
        outline: '#787586',
        'on-surface': '#191a2e',
        'secondary-fixed-dim': '#eac333',
        'surface-variant': '#e1e0fc',
        'surface-container-high': '#e7e6ff',
        'surface-dim': '#d9d7f3',
        secondary: '#725c00',
        'on-primary-container': '#fffbff',
        'surface-container-highest': '#e1e0fc',
        'primary-fixed-dim': '#c6c0ff',
        tertiary: '#5a5a68',
        'on-tertiary-fixed-variant': '#454653',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#c6c5d5',
        'on-tertiary-fixed': '#1a1b26',
        'inverse-primary': '#c6c0ff',
        'on-secondary-fixed': '#231b00',
        'surface-tint': '#5744db',
        'on-tertiary-container': '#fefbff',
        primary: '#5441d8',
        'primary-fixed': '#e4dfff',
        'primary-container': '#6d5df2',
        'tertiary-fixed': '#e2e1f1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '24': '24px',
      },
      spacing: {
        unit: '8px',
        'container-padding': '24px',
        gutter: '24px',
        'section-gap': '64px',
        xl: '80px',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '1.3', fontWeight: '700' },
        ],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-xl': [
          '48px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
